version: "3.8"
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - osmanli-internal-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - osmanli-internal-network
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    command:
      - -config.file=/etc/loki/loki-config.yml
      - -config.expand-env=true
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    restart: unless-stopped
    networks:
      - osmanli-internal-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - osmanli-internal-network
volumes:
  grafana_data: null
networks:
  osmanli-internal-network:
    external: true
